### ISSUE TITLE
Documentation Does Not Explain Required Feature-Hooks

### ISSUE THREAD

**Issue by ghost** [novocaine/rust-python-ext#16]
I discovered through trial and error, and looking at the code, and figuring out how Rust handles features....etc.. that this project requires the inclusion of top-level features in the user's package, `python27-sys` and `python3-sys`, which shadow and include the `cpython` features of the same names. Without these hooks, if I'm not mistaken, rust-ext can't build a library correctly according to the python version that runs the `setup.py`.

The docs should probably explain a bit of the magic behind `rust-ext`; I'm happy to contribute, when I've finally got a stable project built on `rust-ext` in my repertoire!

**Comment by novocaine** [comment]
agree that the docs could include a howto for pythonXX-sys. but the example code does demonstrate how. perhaps this isn't clear.

all this helper does is run cargo for you. it is not coupled to pythonXX-sys - deliberately - so for example you can use it to build a rust lib that you interact with via ctypes or cffi (in fact I think I prefer this model; we should also have an example of doing that)

**Comment by ghost** [comment]
Well, I just mean that at build-time, this library defines a Cargo feature flag depending on the interpreter that runs it. Indeed, it seems to throw an exception if a version of python unsupported by pythonX-sys is used. So it is somewhat tied to the `cpython` crate, but that's fine by me; that's what I intend to use. :)

However, my problems here were complicated by something else; I was using the *PyPI* version of rust-ext, which didn't even define these flags, so I was looking at the Github code trying to find out why it was breaking. :) I just installed from the latest commit using pip, and I've got different problems.. but I'll see how manageable they are.

I'll close this until I have a well formed issue again, but right now I'd just like to point out; this needs a fresh push to PyPI, because the version there is very different!

**Comment by novocaine** [comment]
I had no intention of putting this on pip - but it appears someone else has done so. Thanks for bringing that to my attention.
